-- Migration generated by AI.
-- This migration adds a 'member_resources' table for downloadable content.

CREATE TABLE public.member_resources (
    id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT,
    file_name TEXT,
    file_type TEXT,
    file_size BIGINT,
    file_url TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

-- Enable RLS on member_resources
ALTER TABLE public.member_resources ENABLE ROW LEVEL SECURITY;

-- Create policies for member_resources
CREATE POLICY "Public can view member resources"
ON public.member_resources
FOR SELECT
USING (true);

CREATE POLICY "Admins can manage member resources"
ON public.member_resources
FOR ALL
USING (public.has_role(auth.uid(), 'admin'::app_role))
WITH CHECK (public.has_role(auth.uid(), 'admin'::app_role));