-- Migration generated by AI.
-- This migration adds a 'prayer_requests' table for community engagement.

CREATE TABLE public.prayer_requests (
    id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL, -- Optional: for logged-in users
    name TEXT NOT NULL,
    request TEXT NOT NULL,
    is_public BOOLEAN DEFAULT true,
    is_answered BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

-- Enable RLS on prayer_requests
ALTER TABLE public.prayer_requests ENABLE ROW LEVEL SECURITY;

-- Create policies for prayer_requests
CREATE POLICY "Public can view public prayer requests"
ON public.prayer_requests
FOR SELECT
USING (is_public = true);

CREATE POLICY "Anyone can submit a prayer request"
ON public.prayer_requests
FOR INSERT
WITH CHECK (true);

CREATE POLICY "Admins can manage all prayer requests"
ON public.prayer_requests
FOR ALL
USING (public.has_role(auth.uid(), 'admin'::app_role))
WITH CHECK (public.has_role(auth.uid(), 'admin'::app_role));

CREATE POLICY "Users can view their own prayer requests"
ON public.prayer_requests
FOR SELECT
USING (auth.uid() = user_id);