// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qgzkrspvlyrcebemnmhe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFnemtyc3B2bHlyY2ViZW1ubWhlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1MDU3NDUsImV4cCI6MjA3MDA4MTc0NX0.LYgDGrtY9HF6qJuaY_5yX-nOWOsbVlENSD3F57W5djo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});